import "./globals.css";
import { ReactNode } from "react";
import { Providers } from "@/components/Providers";
import { Analytics } from "@vercel/analytics/next";
import { GoogleAnalytics } from "@next/third-parties/google";

const SITE_URL = "https://metascienceobservatory.org";
const TITLE = "The Metascience Observatory | Analyzing Scientific Reproducibility";
const DESCRIPTION =
  "Using AI to analyze every scientific paper to assess reproducibility, rigor, and fraud across all fields of science.";
// Social link-preview card (1200x630), generated by scripts/build_og_card.py.
// Without an explicit og:image, Facebook/Messenger falls back to scraping the
// page and upscales the globe favicon into an unreadable blur.
const OG_IMAGE = {
  url: "/assets/og-card.png",
  width: 1200,
  height: 630,
  alt: "The Metascience Observatory — analyzing scientific reproducibility, rigor, and fraud across all fields of science",
};

export const metadata = {
  // Required so Next.js emits absolute og:image URLs; scrapers reject relative ones.
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    type: "website",
    siteName: "The Metascience Observatory",
    url: "/",
    locale: "en_US",
    title: TITLE,
    description: DESCRIPTION,
    images: [OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: [OG_IMAGE],
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/assets/globe.svg" type="image/svg+xml" />
        <link rel="icon" href="/assets/globe.png" type="image/png" />
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
        <Analytics />
        {process.env.NEXT_PUBLIC_GA_ID && (
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
        )}
      </body>
    </html>
  );
}


